version: '3.8'

services:
  db:
    container_name: db
    image: mysql
    restart: always
    tty: true
    ports:
      - 3009:3006
    volumes: 
      - ./docker/dbdata:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=lutoparental
      - MYSQL_ROOT_PASSWORD=Lut0P@rentaL
      - MYSQL_USER=user-parental
    
    networks:
      - luto_parental

networks:
  luto_parental:
    external: true
